/**
 * CSV headers for Atlas twins and country bundles.
 * Tests snapshot these arrays so a column change is deliberate.
 * Provenance columns are source_ids, snapshot_label, evidence_status, and the record identifiers.
 */

export const PROVENANCE_COLUMNS = [
  "source_ids",
  "snapshot_label",
  "evidence_status",
  "record_id",
  "release_id",
] as const;

export const JURISDICTION_PAGE_CSV_HEADER = [
  "row_kind",
  "name",
  "level",
  "slug_path",
  "jurisdiction_key",
  "office_id",
  "id_namespace",
  "held_by",
  "since",
  "last_share",
  "last_share_unit",
  "cycle_key",
  "iso_date",
  "contest_count",
  "label",
  "source_ids",
  "snapshot_label",
  "evidence_status",
  "record_id",
  "release_id",
] as const;

export const SEAT_PAGE_CSV_HEADER = [
  "cycle",
  "winner",
  "party",
  "votes",
  "share",
  "margin",
  "turnout",
  "source_ids",
  "snapshot_label",
  "evidence_status",
  "event_id",
  "history_key",
  "office_id",
  "id_namespace",
  "result_row_id",
  "record_id",
  "release_id",
] as const;

export const CYCLE_PAGE_CSV_HEADER = [
  "contest",
  "candidate_or_list",
  "party",
  "votes",
  "votes_status",
  "share",
  "share_status",
  "share_unit",
  "seats",
  "seats_status",
  "elected",
  "source_ids",
  "snapshot_label",
  "evidence_status",
  "event_id",
  "history_key",
  "office_id",
  "id_namespace",
  "result_row_id",
  "record_id",
  "release_id",
] as const;

export const PERSON_CSV_HEADER = [
  "person_id",
  "slug",
  "canonical_label",
  "country_id",
  "review_status",
  "alias_labels",
  "year",
  "election",
  "seat",
  "result",
  "votes",
  "share",
  "margin",
  "source_ids",
  "snapshot_label",
  "evidence_status",
  "record_id",
  "release_id",
] as const;

export const BUNDLE_JURISDICTION_HEADER = [
  "jurisdiction_key",
  "country_id",
  "geography_id",
  "parent_key",
  "depth",
  "level_label",
  "name",
  "slug",
  "slug_path",
  "office_count",
  "event_count",
  "first_event_year",
  "last_event_year",
  "coverage_status",
  "ambiguous",
  ...PROVENANCE_COLUMNS,
] as const;

export const BUNDLE_SEAT_HEADER = [
  "id_namespace",
  "office_id",
  "country_id",
  "office_name",
  "current_holder_label",
  "current_holder_party_label",
  "current_since_date_id",
  "last_selected_event_id",
  "last_share",
  "last_share_unit",
  "last_margin",
  "next_date_id",
  "status_reason",
  ...PROVENANCE_COLUMNS,
] as const;

export const BUNDLE_CYCLE_HEADER = [
  "cycle_key",
  "country_id",
  "date_id",
  "iso_date",
  "contest_count",
  "scope_key",
  "tiers",
  "kinds",
  "label",
  ...PROVENANCE_COLUMNS,
] as const;

export const BUNDLE_CONTEST_HEADER = [
  "country_id",
  "id_namespace",
  "office_id",
  "office_name",
  "event_id",
  "history_key",
  "iso_date",
  "candidate_or_list",
  "party",
  "votes",
  "votes_status",
  "share",
  "share_status",
  "share_unit",
  "seats",
  "seats_status",
  "elected_flag",
  "source_ids",
  "snapshot_label",
  "evidence_status",
  "result_row_id",
  "record_id",
  "release_id",
] as const;

export const BUNDLE_UNPLACED_HEADER = [
  "id_namespace",
  "office_id",
  "history_key",
  "country_id",
  "year",
  "date_id",
  "date_precision",
  "date_resolution",
  ...PROVENANCE_COLUMNS,
] as const;
